#!/usr/bin/env python3
"""Builds assets/logo.svg: the scene around the 3D catamaran.

    python3 tools/logo/build.py   (then: go generate ./cmd/windstream)
"""
import os
import subprocess
import sys

here = os.path.dirname(os.path.abspath(__file__))
boat = subprocess.run([sys.executable, os.path.join(here, 'catamaran.py')],
                      check=True, capture_output=True, text=True).stdout

svg = '''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" width="256" height="256">
  <!-- Windstream: a catamaran charging down the face of a breaking wave,
       seen from the trough just in front of it, about to pass close on our
       right. Generated by tools/logo/build.py; edit there. -->
  <defs>
    <clipPath id="tile"><rect width="256" height="256" rx="56"/></clipPath>
    <linearGradient id="sky" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#0a1736"/>
      <stop offset="0.6" stop-color="#25578a"/>
      <stop offset="1" stop-color="#f2a65a"/>
    </linearGradient>
    <radialGradient id="sun" cx="0.86" cy="0.2" r="0.42">
      <stop offset="0" stop-color="#ffe2a8"/>
      <stop offset="0.25" stop-color="#ffc574" stop-opacity="0.85"/>
      <stop offset="1" stop-color="#ffc574" stop-opacity="0"/>
    </radialGradient>
    <linearGradient id="face" x1="0.1" y1="0" x2="0.4" y2="1">
      <stop offset="0" stop-color="#8ff5e6"/>
      <stop offset="0.3" stop-color="#1fb9ac"/>
      <stop offset="0.7" stop-color="#0b5d7c"/>
      <stop offset="1" stop-color="#05243f"/>
    </linearGradient>
    <linearGradient id="lip" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="#d4fffa"/>
      <stop offset="1" stop-color="#2cc7b8"/>
    </linearGradient>
    <linearGradient id="trough" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#0b4f6c"/>
      <stop offset="1" stop-color="#021427"/>
    </linearGradient>
  </defs>
  <g clip-path="url(#tile)">
    <rect width="256" height="256" fill="url(#sky)"/>
    <rect width="256" height="256" fill="url(#sun)"/>

    <!-- the wave towering over us; its face is behind the boat -->
    <path fill="url(#face)" d="M-4 58 C40 40 84 46 118 66 C156 88 204 104 260 100 L260 260 L-4 260 Z"/>
    <!-- the lip throwing forward over the top left, a hollow tube beneath -->
    <path fill="#0a4f6a" opacity="0.9" d="M-4 70 C44 46 96 34 126 50 C138 58 140 72 132 80
      C120 92 96 94 70 88 C40 82 16 86 -4 96 Z"/>
    <path fill="url(#lip)" d="M-4 26 C40 6 96 4 128 22 C150 34 160 58 152 76
      C148 86 136 88 132 80 C140 72 138 58 126 50 C96 34 44 46 -4 70 Z"/>
    <path fill="none" stroke="#f4feff" stroke-width="5" stroke-linecap="round"
      d="M96 10 C124 16 148 36 154 62"/>
    <path fill="#f4feff" d="M152 60 C158 70 156 82 146 86 C138 88 132 84 132 80
      C140 80 146 74 146 66 Z"/>
    <path fill="none" stroke="#f0fdff" stroke-width="3" stroke-linecap="round" opacity="0.7"
      d="M4 24 C30 8 60 4 90 10"/>
    <g fill="#f0fdff">
      <circle cx="162" cy="58" r="2.6" opacity="0.85"/>
      <circle cx="166" cy="72" r="2" opacity="0.75"/>
      <circle cx="150" cy="30" r="2" opacity="0.7"/>
      <circle cx="140" cy="16" r="1.6" opacity="0.6"/>
      <circle cx="160" cy="42" r="1.4" opacity="0.6"/>
    </g>
    <!-- streaks running down the face -->
    <path fill="none" stroke="#9ff7ea" stroke-width="2" stroke-linecap="round" opacity="0.35"
      d="M20 110 C40 130 52 150 58 176 M60 100 C76 122 86 144 90 168"/>

    <!-- the trough we are sitting in -->
    <path fill="url(#trough)" d="M-4 206 C40 194 90 206 136 198 C184 190 222 198 260 192 L260 260 L-4 260 Z"/>
    <path fill="none" stroke="#5eead4" stroke-width="2.4" stroke-linecap="round" opacity="0.45"
      d="M12 222 C38 216 58 224 84 218 M30 244 C56 238 80 246 106 240"/>

    <!-- the catamaran -->
''' + boat + '''
    <!-- spray flung off the bows toward us -->
    <g fill="#f0fdff">
      <path opacity="0.9" d="M172 204 C182 214 198 220 216 218 C202 226 182 224 168 212 Z"/>
      <path opacity="0.9" d="M214 202 C222 212 236 216 252 214 C240 222 222 222 210 212 Z"/>
      <circle cx="232" cy="234" r="4.2" opacity="0.8"/>
      <circle cx="214" cy="242" r="2.8" opacity="0.7"/>
      <circle cx="246" cy="226" r="2.2" opacity="0.8"/>
      <circle cx="192" cy="232" r="2" opacity="0.6"/>
      <circle cx="168" cy="226" r="1.6" opacity="0.5"/>
    </g>
  </g>
</svg>
'''
out = os.path.join(here, '..', '..', 'assets', 'logo.svg')
with open(out, 'w') as f:
    f.write(svg)
print('wrote', os.path.normpath(out))
